---
title: "lmem-plots"
author: "Ian Malone"
date: "5/12/2021"
output: html_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(stringr)
library(scales)

#dff <- read.csv("C:\\Users\\iangm\\Google Drive\\IanGMalone\\UF\\Lab\\Neilsen_Project_Files\\NEW-NEW-lmem-plotting.csv") #laptop
dff <- read.csv("C:\\Users\\Ian\\Google Drive\\IanGMalone\\UF\\Lab\\Neilsen_Project_Files\\NEW-NEW-lmem-plotting.csv") #desktop

df1 <- dff %>%
  mutate(Day = as_factor(Day)) %>%
  filter(str_detect(Predictor, '\\*'))


```


#### COMPARISON C2HS+EES vs. NoInj+EES FOR EACH DAY ####
```{r}

df =
  df1 %>%
  filter(Model == 'C2HS+EES vs. NoInj+EES') %>%
   filter(Side == 'Left')


ggplot(df) + 
geom_pointrange(aes(x=Day, y=New_Estimate, ymin=new_ci_low, ymax=new_ci_high, color=Predictor), position = position_dodge(width = 1), size=1) + 
 # facet_grid(cols=vars(Side)) +
        scale_x_discrete(labels = wrap_format(10)) + geom_text(data=subset(df, Predictor == 'Stim_Amp [log] * Injury[Yes]'), aes(Day,New_Estimate, label = P_Label), size=7) +
  ylab('Sensitivity (a.u.)') +
  ggtitle('C2HS+EES vs. NoInj+EES') +
  theme_classic() + theme(text = element_text(size = 20), legend.text = element_blank()) +  scale_color_manual(values=cbPalette)

ggsave("D:\\gg4.png")

```




#### COMPARISON C2HS+Sham vs. C2HS+EES FOR EACH DAY ####
```{r}
# The palette with grey:
cbPalette <- c('#D81B60', '#1E88E5', '#FFC107', '#004D40')

# To use for fills, add
#  scale_fill_manual(values=cbPalette)

# To use for line and point colors, add
#  scale_color_manual(values=cbPalette)

df =
  df1 %>%
  filter(Model == 'C2HS+Sham vs. C2HS+EES') %>%
   filter(Side == 'Left')



ggplot(df) + 
geom_pointrange(aes(x=Day, y=New_Estimate, ymin=new_ci_low, ymax=new_ci_high, color=Predictor), position = position_dodge(width = 1), size=1) + 
 # facet_grid(cols=vars(Side)) +
        scale_x_discrete(labels = wrap_format(10))+
  geom_text(data=subset(df, Predictor == 'Stim_Amp [log] * Therapy[Yes]'), aes(Day,New_Estimate, label = P_Label), size=7) +
    ylab('Sensitivity (a.u.)') +
  ggtitle('C2HS+EES vs. C2HS+Sham') +
  theme_classic() + theme(text = element_text(size = 20), legend.text = element_blank()) +  scale_color_manual(values=cbPalette)

ggsave("D:\\gg3.png")

```




#### COMPARISON Left vs. Right FOR EACH DAY ####
```{r}

df =
  df1 %>%
  filter(Model == 'Left vs. Right') %>%
  filter(Group == 'C2HS+EES')

ggplot(df) + 
geom_pointrange(aes(x=Day, y=New_Estimate, ymin=new_ci_low, ymax=new_ci_high, color=Predictor), position = position_dodge(width = 1), size=1) + 
  #facet_grid(cols=vars(Group))+
        scale_x_discrete(labels = wrap_format(10)) + 
  geom_text(data=subset(df, Predictor == 'Stim_Amp [log] * Side[Left]'), aes(Day,New_Estimate, label = P_Label), size=7) +
      ylab('Sensitivity (a.u.)') +
  ggtitle('Left vs. Right') +
  theme_classic() + theme(text = element_text(size = 20), legend.text = element_blank()) +  scale_color_manual(values=cbPalette)

ggsave("D:\\gg2.png")


```






#### COMPARISON BETWEEN DayS FOR EACH GROUP AND SIDE ####
```{r}

df =
  df1 %>%
  filter(Model == 'Day [4,3,2] vs. Day 1')%>%
  filter(Side == 'Left')%>%
  filter(Group == 'C2HS+EES')

ggplot(df) + 
geom_pointrange(aes(x=Predictor, y=New_Estimate, ymin=new_ci_low, ymax=new_ci_high, color=Predictor), position = position_dodge(width = 1), size=1) + 
 # facet_grid(rows=vars(Group), cols=vars(Side)) +
      scale_x_discrete(labels = wrap_format(10)) +
  geom_text(data=subset(df, Predictor %in% c('Stim_Amp [log] * Day [2]', 'Stim_Amp [log] * Day [3]', 'Stim_Amp [log] * Day [4]')), 
            aes(Predictor,New_Estimate, label = P_Label),hjust=-0.25, vjust=-0.5, size=7) +
        ylab('Sensitivity (a.u.)') +
  ggtitle('Change from Day 1') +
  theme_classic() + theme(text = element_text(size = 20), legend.text = element_blank()) +  scale_color_manual(values=cbPalette) + scale_x_discrete(labels=c('Stim_Amp [log] * Day [1]' = "1", 'Stim_Amp [log] * Day [2]' = "2",
                              'Stim_Amp [log] * Day [3]' = "3", 'Stim_Amp [log] * Day [4]' = "4"))

ggsave("D:\\gg1.png")


```
