---
title: "Report"
author: "Sijia Yue"
date: "3/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lme4)
library(tidyverse)
library(sjPlot)

df_p2p_scaled1 <- read.csv(file = 'D:\\Neilsen\\Dataframes\\df_auc_right.csv')

df_p2p_scaled <- df_p2p_scaled1 %>%
  mutate(Day = as_factor(Day)) %>% 
  mutate(Injury = if_else(str_detect(Group, "Yes Injury"), "Yes", "No"),
         Therapy = if_else(str_detect(Group, "Yes EES"), "Yes", "No"),
         p2p = Scalar_Original_Value*10000) 

df_no_injury = df_p2p_scaled %>% 
  filter(Injury == "No")

df_yes_injury = df_p2p_scaled %>% 
  filter(Injury == "Yes")
```

## Compare yes injury no stimulation vs yes injury yes stimulation

### Day 4
```{r}
df_d4 = 
  df_yes_injury %>% 
  filter(Day == 4)

# New version
fit4 = lmer(p2p ~ log(Stim_Amp) * Therapy + (0 + log(Stim_Amp) |Animal), data=df_d4, REML = F)
tab_model(fit4, show.icc = FALSE, show.re.var = FALSE)
summary(fit4)
```

### Day 3
```{r}
df_d3 = 
  df_yes_injury %>% 
  filter(Day == 3)

fit3 = lmer(p2p ~ log(Stim_Amp) * Therapy + (0 + log(Stim_Amp) |Animal), data=df_d3)
tab_model(fit3, show.icc = FALSE, show.re.var = FALSE)
summary(fit3)
```

### Day 2
```{r}
df_d2 = 
  df_yes_injury %>% 
  filter(Day == 2)

fit2 = lmer(p2p ~ log(Stim_Amp) * Therapy + (0 + log(Stim_Amp) |Animal), data=df_d2)
tab_model(fit2, show.icc = FALSE, show.re.var = FALSE)
summary(fit2)
```

### Day 1
```{r}
df_d1 = 
  df_yes_injury %>% 
  filter(Day == 1)

fit1 = lmer(p2p ~ log(Stim_Amp) * Therapy + (0 + log(Stim_Amp) |Animal), data=df_d1)
tab_model(fit1, show.icc = FALSE, show.re.var = FALSE)
summary(fit1)
```

## Compare yes injury yes stimulation vs no injury yes stimulation

### Day 4
```{r}
df_model2 = 
  df_p2p_scaled %>% 
  filter(Therapy == "Yes")

df_day = 
  df_model2 %>% 
  filter(Day==4)
fit = lmer(p2p ~ log(Stim_Amp) * Injury + (0 + log(Stim_Amp)|Animal), data=df_day)
summary(fit)
tab_model(fit, show.icc = FALSE, show.re.var = FALSE)
```

### Day 3
```{r}
df_day = 
  df_model2 %>% 
  filter(Day==3)

fit = lmer(p2p ~ log(Stim_Amp) * Injury + (0 + log(Stim_Amp)|Animal), data=df_day)
summary(fit)
tab_model(fit, show.icc = FALSE, show.re.var = FALSE)
```

### Day 2
```{r}
df_day = 
  df_model2 %>% 
  filter(Day==2)

fit = lmer(p2p ~ log(Stim_Amp) * Injury + (0 + log(Stim_Amp)|Animal), data=df_day)
summary(fit)
tab_model(fit, show.icc = FALSE, show.re.var = FALSE)
```

### Day 1
```{r}
df_day = 
  df_model2 %>% 
  filter(Day==1)

fit = lmer(p2p ~ log(Stim_Amp) * Injury + (0 + log(Stim_Amp)|Animal), data=df_day)
summary(fit)
tab_model(fit, show.icc = FALSE, show.re.var = FALSE)
```

